services:
  - type: web
    name: NoraIA
    runtime: python
    plan: free
    region: oregon

    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"

    envVars:
      # FastAPI / App
      - key: FRONTEND_URL
        sync: false

      # Oracle DB
      - key: ORACLE_USER
        sync: false
      - key: ORACLE_PASSWORD
        sync: false
      - key: ORACLE_DSN
        sync: false

      # Seguran√ßa / JWT
      - key: JWT_SECRET
        sync: false
      - key: JWT_ALGORITHM
        sync: false
      - key: JWT_EXPIRATION_MINUTES
        sync: false
